name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'busybox-chart/**'
  pull_request:
    branches:
      - main
    paths:
      - 'busybox-chart/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Get current chart version
        id: get_version
        run: |
          VERSION=$(grep '^version:' busybox-chart/Chart.yaml | awk '{print $2}')
          echo "Current chart version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Increment Chart Version
        id: increment_version
        run: |
          VERSION=$(echo ${{ env.VERSION }} | awk -F. -v OFS=. '{$NF++; print $0}')
          echo "New version: $VERSION"
          sed -i "s/^version: ${{ env.VERSION }}/version: $VERSION/" busybox-chart/Chart.yaml
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit Updated Chart.yaml
        run: |
          git config --global user.name "ramy"
          git config --global user.email "rmrbnd@gmail.com"
          git add busybox-chart/Chart.yaml
          git commit -m "Bump Helm chart version to ${{ env.VERSION }}" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Package Helm Chart
        run: |
          helm package busybox-chart -d busybox-docs/
          helm repo index busybox-docs --url https://ramyerubandi1.github.io/busybox-docs/

      - name: Commit and Push Packaged Chart
        run: |
          git config --global user.name "ramy"
          git config --global user.email "rmrbnd@gmail.com"
          git add busybox-docs/
          git commit -m "Auto-publish Helm chart version ${{ env.VERSION }}" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
